---
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL}
      - GITEA__server__SSH_DOMAIN=${GITEA_SSH_DOMAIN}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT}
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - gitea
    volumes:
      - ${GITEA_DATA_VOLUME}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_WEB_UI_PORT}:3000"       # Gitea Web UI
      - "${GITEA_SSH_PORT}:22"            # SSH for Git

  db:
    image: postgres:15-alpine
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME}
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
    networks:
      - gitea
    volumes:
      - ${GITEA_DATA_VOLUME}/postgres:/var/lib/postgresql/data

networks:
  gitea:
